CREATE TABLE IF NOT EXISTS `Courses` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`code` CHAR(8) NOT NULL,
	`name` VARCHAR(255),
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `Prerequisites` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`course_id` INTEGER NOT NULL,
	`prereq_course_id` INTEGER NOT NULL,
	PRIMARY KEY(`id`)
);


ALTER TABLE `Prerequisites`
ADD FOREIGN KEY(`course_id`) REFERENCES `Courses`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Prerequisites`
ADD FOREIGN KEY(`prereq_course_id`) REFERENCES `Courses`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;